# Project-wide Gradle settings.

# JVM / mémoire
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Architectures ciblées (pour réduire la taille de l'APK)
reactNativeArchitectures=arm64-v8a

# Activer nouvelle architecture (TurboModules/Fabric si nécessaire)
newArchEnabled=false

# Moteur JS
hermesEnabled=true

# Edge-to-edge UI (désactivé ici)
edgeToEdgeEnabled=false

# ===== SIGNATURE APK RELEASE =====
MYAPP_UPLOAD_STORE_FILE=debug.keystore
MYAPP_UPLOAD_KEY_ALIAS= androiddebugkey
MYAPP_UPLOAD_STORE_PASSWORD=android
MYAPP_UPLOAD_KEY_PASSWORD=android
